<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class InstitutionAreaCareerSemesterSubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->insertInstitution();
        $this->insertArea();
        $this->insertCareer();
        $this->insertSemester();
        $this->insertVenuesCareers();
        $this->insertSemestersCareers();
        $this->insertSubject();
        $this->insertCareersSubjects();
        $this->insertSubjectSemesters();
    }

    public function insertInstitution(): void
    {
        $now = now();
        $institutions = [
            ['Instituto Profesional INACAP', 'IP'],
            ['Centro de Formacion Tecnica INACAP', 'CFT'],
            ['Universidad INACAP', 'U'],
        ];

        $institutions = array_map(function ($institution) use ($now){
            return [
                'name' => $institution[0],
                'abr' => $institution[1],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $institutions);

        DB::table('institutions')->insert($institutions);
    }

    public function insertArea(): void
    {
        $now = now();
        $areas = [
            ['Administracion', 'Administracion y Servicios'],
            ['Diseño', 'Administracion y Servicios'],
            ['Hoteleria, Turismo y Gastronomia', 'Administracion y Servicios'],
            ['Humanidades', 'Administracion y Servicios'],
            ['Salud', 'Administracion y Servicios'],
            ['Automotizacion y Robotica', 'Tecnologia Aplicada'],
            ['Electricidad, Electronica y Telecomunicaciones', 'Tecnologia Aplicada'],
            ['Tecnologias de Informacion y Ciberseguridad', 'Tecnologia Aplicada'],
            ['Agroindustria y Medioambiente', 'Energia y Sustentabilidad'],
            ['Construccion', 'Energia y Sustentabilidad'],
            ['Eficiencia Energetica', 'Energia y Sustentabilidad'],
            ['Logistica', 'Mantenimiento y Logistica'],
            ['Mecanica', 'Mantenimiento y Logistica'],
            ['Mineria', 'Mantenimiento y Logistica'],
        ];

        $areas = array_map(function ($area) use ($now){
            return [
                'name' => $area[0],
                'description' => $area[1],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $areas);

        DB::table('areas')->insert($areas);
    }

    public function insertCareer(): void
    {
        #IP = 1
        #CFT = 2
        $now = now();
        $careers = [
            ['Administracion de Empresas',2,1],
            ['Contabilidad General',2,1],
            ['Contador Publico',1,1],
            ['Ingenieria en Administracion de Empresas',1,1],
            ['Administracion Gastronomica Internacional',1,3],
            ['Administracion Turistica Internacional',1,3],
            ['Gastronomia Internacional',2,3],
            ['Turismo',2,3],
            ['Laboratorista Clinico Banco de Sangre e Imagenologia',2,5],
            ['Tecnico en Enfermeria',2,5],
            ['Ternico en Farmacia',2,5],
            ['Ternico en Odontologia',2,5],
            ['Ingenieria en Automatizacion y Robotica',1,6],
            ['Tecnico en Automatizacion y Robotica',2,6],
            ['Electricidad Industrial',2,7],
            ['Electronica',2,7],
            ['Ingenieria en Telecomunicaciones, Conectividad y Redes',1,7],
            ['Ingenieria Electrica',1,7],
            ['Ingenieria en Electronica y Sistemas Inteligentes',1,7],
            ['Telecomunicaciones, Conectividad y Redes',2,7],
            ['Analista Programador',2,8],
            ['Ingenieria en Informatica',1,8],
            ['Ingenieria Agricola',1,9],
            ['Tecnologia Agricola',2,9],
            ['Construccion Civil',1,10],
            ['Fabricacion y Montaje Industrial',2,10],
            ['Ingenieria en Geomensura',1,10],
            ['Tecnico en Construccion',2,10],
            ['Topografia',2,10],
            ['Ingenieria en Logistica',1,12],
            ['Tecnico en Logistica',2,12],
            ['Electromecanica',2,13],
            ['Ingenieria en Maquinaria Pesxzada y Vehiculos Automotrices',1,13],
            ['Ingenieria en Mecanica y Electromovilidad Automotriz',1,13],
            ['Ingenieria Mecanica en Mantenimiento Industrial',1,13],
            ['Mantenimiento Industrial',2,13],
            ['Mecanica Automotriz en Maquinaria Pesada',2,13],
            ['Tecnico en Mecanica y Electromovilidad Automotriz',2,13],
            ['Ingenieria en Metalurgia',1,14],
            ['Ingenieria en Minas',1,14],
            ['Tecnico en Metalurgia Extractiva',2,14],
            ['Tecnico en Mineria',2,14],

        ];

        $careers = array_map(function ($career) use ($now){
            return [
                'name' => $career[0],
                'slug' =>  Str::lower(str_replace(' ','-',$career[0])),
                'institution_id' => $career[1],
                'area_id' => $career[2],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $careers);

        DB::table('careers')->insert($careers);
    }

    public function insertSemester(): void
    {
        $now = now();
        $semesters = [
            ['Primer Semestre'],
            ['Segundo Semestre'],
            ['Tercer Semestre'],
            ['Cuarto Semestre'],
            ['Quinto Semestre'],
            ['Sexto Semestre'],
            ['Septimo Semestre'],
            ['Octavo Semestre'],
            ['Sin Notificar']
        ];

        $semesters = array_map(function ($semester) use ($now){
            return [
                'name' => $semester[0],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $semesters);

        DB::table('semesters')->insert($semesters);
    }

    public function insertVenuesCareers(): void
    {
        $now = now();
        $venues_careers = [
            [2,1],
            [2,4],
            [2,6],
            [2,7],
            [2,8],
            [2,13],
            [2,14],
            [2,21],
            [2,22],
            [2,25],
            [2,29],
            [2,31],
            [2,34],
            [2,38],
            [3,42],
            [3,38],
            [3,31],
            [3,14],
            [3,37],
            [3,36],
            [3,35],
            [3,40],
            [3,39],
            [3,34],
            [3,33],
            [3,30],
            [3,22],
            [3,13],
            [3,4],
            [3,7],
            [3,15],
            [3,3],
            [3,2],
            [3,25],
            [3,21],
            [3,5],
            [3,1],
            [4,8],
            [4,41],
            [4,31],
            [4,14],
            [4,37],
            [4,36],
            [4,35],
            [4,40],
            [4,39],
            [4,33],
            [4,22],
            [4,13],
            [4,4],
            [4,7],
            [4,2],
            [4,21],
            [4,1],
            [5,1],
            [5,5],
            [5,21],
            [5,15],
            [5,7],
            [5,18],
            [5,4],
            [5,13],
            [5,22],
            [5,33],
            [5,34],
            [5,39],
            [5,40],
            [5,35],
            [5,36],
            [5,37],
            [5,14],
            [5,31],
            [5,41],
            [5,42],
            [6,1],
            [6,21],
            [6,2],
            [6,32],
            [6,7],
            [6,4],
            [6,22],
            [6,33],
            [6,34],
            [6,40],
            [6,37],
            [6,10],
            [6,31],
            [6,38],
            [6,42],
            [7,1],
            [7,5],
            [7,21],
            [7,25],
            [7,2],
            [7,3],
            [7,32],
            [7,7],
            [7,4],
            [7,27],
            [7,22],
            [7,30],
            [7,34],
            [7,17],
            [7,37],
            [7,28],
            [7,10],
            [7,31],
            [7,38],
            [7,20],
            [7,11],
            [7,29],
            [7,8],
            [8,1],
            [8,5],
            [8,21],
            [8,25],
            [8,2],
            [8,15],
            [8,16],
            [8,7],
            [8,18],
            [8,4],
            [8,22],
            [8,34],
            [8,17],
            [8,35],
            [8,36],
            [8,14],
            [8,10],
            [8,38],
            [8,20],
            [8,11],
            [8,12],
            [8,8],
            [9,1],
            [9,5],
            [9,6],
            [9,21],
            [9,3],
            [9,7],
            [9,23],
            [9,4],
            [9,22],
            [9,8],
            [10,1],
            [10,5],
            [10,21],
            [10,25],
            [10,2],
            [10,32],
            [10,7],
            [10,4],
            [10,13],
            [10,27],
            [10,22],
            [10,30],
            [10,34],
            [10,35],
            [10,36],
            [10,14],
            [10,28],
            [10,10],
            [10,31],
            [10,38],
            [10,11],
            [10,29],
            [11,1],
            [11,21],
            [11,25],
            [11,15],
            [11,32],
            [11,16],
            [11,26],
            [11,23],
            [11,18],
            [11,13],
            [11,22],
            [11,30],
            [11,33],
            [11,34],
            [11,40],
            [11,17],
            [11,35],
            [11,36],
            [11,37],
            [11,14],
            [11,28],
            [11,31],
            [11,38],
            [11,42],
            [11,24],
            [11,20],
            [12,1],
            [12,6],
            [12,21],
            [12,25],
            [12,15],
            [12,18],
            [12,4],
            [12,27],
            [12,22],
            [12,28],
            [12,29],
            [12,8],
            [13,1],
            [13,21],
            [13,2],
            [13,3],
            [13,4],
            [13,22],
            [13,17],
            [13,9],
            [13,10],
            [13,31],
            [13,20],
            [13,11],
            [13,12],
            [14,1],
            [14,21],
            [14,15],
            [14,16],
            [14,23],
            [14,18],
            [14,4],
            [14,13],
            [14,19],
            [14,22],
            [14,30],
            [14,33],
            [14,17],
            [14,35],
            [14,36],
            [14,14],
            [14,31],
            [14,38],
            [14,24],
            [14,20],
            [15,1],
            [15,21],
            [15,2],
            [15,3],
            [15,15],
            [15,18],
            [15,4],
            [15,13],
            [15,22],
            [15,30],
            [15,34],
            [15,17],
            [15,35],
            [15,36],
            [15,14],
            [15,31],
            [15,38],
            [15,20],
            [16,1],
            [16,6],
            [16,21],
            [16,25],
            [16,2],
            [16,3],
            [16,15],
            [16,32],
            [16,7],
            [16,4],
            [16,13],
            [16,22],
            [16,34],
            [16,35],
            [16,36],
            [16,14],
            [16,31],
            [16,38],
            [16,20],
            [16,11],
            [16,12],
            [16,8],
            [17,1],
            [17,21],
            [17,25],
            [17,2],
            [17,3],
            [17,32],
            [17,7],
            [17,23],
            [17,4],
            [17,13],
            [17,22],
            [17,30],
            [17,34],
            [17,35],
            [17,36],
            [17,14],
            [17,10],
            [17,31],
            [17,38],
            [17,24],
            [18,1],
            [18,5],
            [18,21],
            [18,2],
            [18,7],
            [18,4],
            [18,13],
            [18,22],
            [18,30],
            [18,34],
            [18,35],
            [18,36],
            [18,14],
            [18,28],
            [18,31],
            [18,38],
            [19,1],
            [19,6],
            [19,21],
            [19,25],
            [19,2],
            [19,15],
            [19,7],
            [19,23],
            [19,18],
            [19,4],
            [19,27],
            [19,22],
            [19,34],
            [19,35],
            [19,36],
            [19,37],
            [19,10],
            [19,31],
            [19,38],
            [19,24],
            [19,20],
            [19,29],
            [20,1],
            [20,6],
            [20,21],
            [20,25],
            [20,2],
            [20,15],
            [20,32],
            [20,7],
            [20,23],
            [20,18],
            [20,4],
            [20,13],
            [20,27],
            [20,22],
            [20,34],
            [20,17],
            [20,35],
            [20,36],
            [20,14],
            [20,10],
            [20,31],
            [20,38],
            [20,24],
            [20,20],
            [20,29],
            [20,8],
            [21,1],
            [21,5],
            [21,21],
            [21,25],
            [21,2],
            [21,15],
            [21,32],
            [21,16],
            [21,26],
            [21,7],
            [21,18],
            [21,4],
            [21,13],
            [21,27],
            [21,22],
            [21,34],
            [21,17],
            [21,35],
            [21,36],
            [21,10],
            [21,31],
            [21,38],
            [21,20],
            [21,8],
            [22,1],
            [22,25],
            [22,2],
            [22,15],
            [22,32],
            [22,16],
            [22,18],
            [22,4],
            [22,13],
            [22,19],
            [22,27],
            [22,33],
            [22,35],
            [22,36],
            [22,37],
            [22,14],
            [22,28],
            [22,31],
            [22,29],
            [23,1],
            [23,5],
            [23,21],
            [23,25],
            [23,15],
            [23,16],
            [23,7],
            [23,23],
            [23,4],
            [23,22],
            [23,34],
            [23,17],
            [23,36],
            [23,14],
            [23,28],
            [23,31],
            [23,38],
        ];

        $venues_careers = array_map(function ($venue_career) use ($now){
            return [
                'venue_id' => $venue_career[0],
                'career_id' => $venue_career[1],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $venues_careers);

        DB::table('venues_careers')->insert($venues_careers);
    }

    public function insertSemestersCareers(): void
    {
        $now = now();
        $semesters_careers = [
            [1,21],
            [2,21],
            [3,21],
            [4,21],
            [1,22],
            [2,22],
            [3,22],
            [4,22],
            [5,22],
            [6,22],
            [7,22],
            [8,22],
        ];

        $semesters_careers = array_map(function ($semester_career) use ($now){
            return [
                'semester_id' => $semester_career[0],
                'career_id' => $semester_career[1],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $semesters_careers);

        DB::table('semesters_careers')->insert($semesters_careers);
    }

    public function insertSubject(): void
    {
        $now = now();
        $subjects = [
            ['Formulacion Ciudadana'],
            ['Resolucion de Problemas en Algebra'],
            ['Fundamentos de Base de Datos'],
            ['Introduccion a la Programacion'],
            ['Fundamentos de Hardware y Software'],
            ['Administracion'],
            ['Funciones y Matrices'],
            ['Programacion Orientada a Objeto'],
            ['Bases de Datos Relacionales'],
            ['Desarrollo Agil'],
            ['Sistemas Operativos'],
            ['Ingles I'],
            ['Programacion Front End'],
            ['Bases de Datos no Estructuradas'],
            ['Diseño de Sistemas'],
            ['Electivo de Tendencias del Sector Productivo y de Servicios I'],
            ['Taller de Desarrollo de Aplicaciones'],
            ['Innovacion y emprendimiento I'],
            ['Programacion Back End'],
            ['Aplicaciones para Moviles para IOT'],
            ['Ingenieria de Software'],
            ['Electivo de Tendencias del Sector Productivo y de Servicios II'],
            ['Taller de Diseño y desarrollo de Soluciones'],
            ['Calculo Diferencial'],
            ['Estadistica'],
            ['Innovacion y emprendimiento II'],
            ['Arquitectura y Almacenamiento de Datos'],
            ['Redes de Datos'],
            ['Tecnologia Cloud'],
            ['Finanzas'],
            ['Probabilidad'],
            ['Ingles II'],
            ['Mineria de Datos'],
            ['Seguridad de la Informacion'],
            ['Proyecto de Integracion'],
            ['Evaluacion de Proyectos'],
            ['Ingles III'],
            ['Inteligencia de Negocios'],
            ['Gestion de Proyectos'],
            ['Electivo de Tendencias del Sector Productrivo y de Servicios III'],
            ['Electivo de Tendencias del Sector Productrivo y de Servicios IV'],
            ['Innovacion y Emprendimiento III'],
            ['Big Data'],
            ['Aplicaciones de Inteligencia Artificial'],
            ['Electivo de Tendencias del Sector Productivo y de Servicios V'],
            ['Electivo de Tendencias del Sector Productivo y de Servicios VI'],
            ['Proyecto de Titulo'],
            ['Economia y Negocios'],
            ['Legislacion Comercial y Laboral'],
            ['Aplicaciones Computacionales'],
            ['Contabilidad'],
            ['Gestion de Personas'],
            ['Legislacion Tributaria'],
            ['Funciones y Progresiones'],
            ['Marketing'],
            ['Taller Integrado de Empresas'],
            ['Costo y Presupuesto'],
            ['Estados Financieros'],
            ['Taller de Asistencia Empresarial'],
            ['Ventas y Servicios'],
            ['Software ERP'],
            ['Contabilidad Intermedia'],
            ['Taller Integrado Contable'],
            ['Taller de Tributacion IVA'],
            ['Taller de Asistencia Contable'],
            ['Taller de Tributacion Renta'],
            ['Contabilidad Avanzada'],
            ['Gestion de Costos'],
            ['Finanzas para la Toma de Decisiones'],
            ['Control Interno'],
            ['Contabilidad Superior'],
            ['Economia y Negocios II'],
            ['Renta de Grandes Contribuyentes'],
            ['Taller ed Simulacion de Negocios'],
            ['Auditoria de Estados Financieros'],
            ['Sistemas de Informacion Administrativo'],
            ['Planificacion Estrategica y Control Gestion'],
            ['Taller de Auditoria'],
            ['Taller de Consultoria Contable'],
            ['Etica en los Negocios'],
            ['Marketing Estrategico'],
            ['Liderazgo y Trabajo en Equpo'],
            ['Business Plan'],
            ['Economia para la Gestion'],
            ['Sostenibilidad en los Negocios'],
            ['Taller de Simulacion de Negocios'],
            ['Entorno Economico'],
            ['Estadistica Inferencial'],
            ['Business Analytics'],
            ['Taller de Consultoria Empresarial'],
            ['Introduccion a la Industria del Servicio'],
            ['Autogestion'],
            ['Tecnologias de la Informacion y la Comunicación'],
            ['Frances Culinario I'],
            ['Conservacion ed Alimentos'],
            ['Taller de Tecnicas Basicas de Cocina'],
            ['Taller de Tecnicas Basicas de Pasteleria'],
            ['Taller de Alimentacion Colectiva y Saludable'],
            ['Taller  de Restaurant y Protocolo'],
            ['Frances Culinario II'],
            ['Matematica Aplicada'],
            ['Taller de Panaderia y Botilleria'],
            ['Seguridad Alimentaria y HACCP'],
            ['Costos y Ventas de la Produccion Gastronomica'],
            ['Ingles Hotuga I'],
            ['Comunicación Efectiva'],
            ['Taller de Gastronomia Chilena y LatinoAmericana'],
            ['Materias Primas: Naturaleza y Productos de Chile'],
            ['Taller de Pasteleria, Confiteria y Chocolateria'],
            ['Administrcion de la Operación Gastronomica'],
            ['Ingles Hotuga II'],
            ['Diseño y Equipamiento de Cocina'],
            ['Taller de Gelateria y Pasteleria Internacional'],
            ['Taller Integrador de la Produccion Gastronomica'],
            ['Costos y Adquisiciones'],
            ['Principios de Economia'],
            ['Ingles Culinario III'],
            ['Analisis Estadistico de Datos'],
            ['Frances Culinario III'],
            ['Taller de Artes Culinarias Internacionales'],
            ['Taller de Tecnicas de Pasteleria Avanzada'],
            ['Administracion de Empresas Gastronomicas'],
            ['Marketing y Gestion Comercial'],
            ['Matematica Financiera'],
            ['Ingles Culinario IV'],
            ['Frances Culinario IV'],
            ['Taller de Gastronomia en Restaurant'],
            ['Legislacion Laboral, Alimentaria y Ambiental'],
            ['Ingles Culinario V'],
            ['Formacion y Evaluiacion de Proyectos Gastronomicos'],
            ['Armonizacion de Vinos y Comidas'],
            ['Taller de Productos Gastronomicos Saludables'],
            ['Ingles Culinario VI'],
            ['Desarrollo Profesional'],
            ['Taller de Proyectos Gastronomicos'],
            ['Emprendimiento'],
            ['Catering para Eventos, Congresos y Banqueteria'],

        ];

        $subjects = array_map(function ($subject) use ($now){
            return [
                'name' => $subject[0],
                'slug' => Str::lower(str_replace(' ','-',$subject[0])),
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $subjects);

        DB::table('subjects')->insert($subjects);
    }

    public function insertCareersSubjects(): void
    {
        $now = now();
        $careers_subjects = [
            [21,1],
            [21,2],
            [21,3],
            [21,4],
            [21,5],
            [21,6],
            [21,7],
            [21,8],
            [21,9],
            [21,10],
            [21,11],
            [21,12],
            [21,13],
            [21,14],
            [21,15],
            [21,16],
            [21,17],
            [21,18],
            [21,19],
            [21,20],
            [21,21],
            [21,22],
            [21,23],
            [22,1],
            [22,2],
            [22,3],
            [22,4],
            [22,5],
            [22,6],
            [22,7],
            [22,8],
            [22,9],
            [22,10],
            [22,11],
            [22,12],
            [22,13],
            [22,14],
            [22,15],
            [22,16],
            [22,17],
            [22,18],
            [22,19],
            [22,20],
            [22,21],
            [22,22],
            [22,23],
            [22,24],
            [22,25],
            [22,27],
            [22,28],
            [22,29],
            [22,30],
            [22,31],
            [22,32],
            [22,33],
            [22,34],
            [22,35],
            [22,36],
            [22,37],
            [22,38],
            [22,39],
            [22,40],
            [22,41],
            [22,42],
            [22,43],
            [22,44],
            [22,45],
            [22,46],
            [22,47],
        ];

        $careers_subjects = array_map(function ($career_subject) use ($now){
            return [
                'career_id' => $career_subject[0],
                'subject_id' => $career_subject[1],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $careers_subjects);

        DB::table('careers_subjects')->insert($careers_subjects);
    }

    public function insertSubjectSemesters(): void
    {
        $now = now();
        $subjects_semesters = [
            [1,1],
            [2,1],
            [3,1],
            [4,1],
            [5,1],
            [6,2],
            [7,2],
            [8,2],
            [9,2],
            [10,2],
            [11,2],
            [12,3],
            [13,3],
            [14,3],
            [15,3],
            [16,3],
            [17,3],
            [18,4],
            [19,4],
            [20,4],
            [21,4],
            [22,4],
            [23,4],
            [24,5],
            [25,5],
            [26,5],
            [27,5],
            [28,5],
            [29,5],
            [30,6],
            [31,6],
            [32,6],
            [33,6],
            [34,6],
            [35,6],
            [36,7],
            [37,7],
            [38,7],
            [39,7],
            [40,7],
            [41,7],
            [42,8],
            [43,8],
            [44,8],
            [45,8],
            [46,8],
            [47,8],
        ];

        $subjects_semesters = array_map(function ($subject_semester) use ($now){
            return [
                'subject_id' => $subject_semester[0],
                'semester_id' => $subject_semester[1],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $subjects_semesters);

        DB::table('subjects_semesters')->insert($subjects_semesters);
    }
}
